### ISSUE TITLE
Where are strikes assets?

### ISSUE THREAD

**Issue by PabloRNC** [tailsjs/brawl-stars-assets#10]
Hi, I want to know where I can find assets for strikes of brawl stars

**Comment by tailsjs** [comment]
What is "strikes assets"? What do you mean?

**Comment by PabloRNC** [comment]
I mean where are the assets or the asset of the strikes in brawl stars the ones you gain when you win lots of games without losing any one. I need only the image of the fire that symbolize the strike. Thanks

**Comment by PabloRNC** [comment]
But I don't know where they could be.

**Comment by tailsjs** [comment]
... in ui.sc?

**Comment by PabloRNC** [comment]
In which folder? I found it in CN-55.2.2 or so named but it seems to be more ui.sc? I don't know what each folder represents.

**Comment by PabloRNC** [comment]
I'm trying to extract ui.sc file with tones of programs and applications but when trying to install new version files I'm always getting this error Attempted to read beyond the bounds of the managed data. In older versions this error is not thrown so how I extract newer sc files
