### ISSUE TITLE
Open files

### ISSUE THREAD

**Issue by Pietronux** [tailsjs/brawl-stars-assets#13]
How can i open all 3d files to see content? I've tried to open files on Blender and other software but it doesn't work

**Comment by tailsjs** [comment]
https://github.com/Vorono4ka/scw2obj

**Comment by gcohen-dev** [comment]
Hi ,
This does not work and most of the files are GLB now. 
I will highly appreciate if you can elaborate how to conver the GLB to DAE or some other format we can work with.
Thank you so much for this awesome project.
