### ISSUE TITLE
v41

### ISSUE THREAD

**Issue by Reid1n** [tailsjs/brawl-stars-assets#2]
v41.144: https://drive.google.com/file/d/11Ug69RTl4MIBXgW6ZL6W7_TZV3Q_EuhZ/view?usp=drivesdk

v41.131 & v41.148: https://drive.google.com/file/d/11WD_aUedWkYgk-vqtRGCMyvZO4K4At11/view?usp=drivesdk

**Comment by tailsjs** [comment]
Сяпки, сейчас запушу.
