### ISSUE TITLE
Ассеты с 荒野乱斗账号绑定工具 v48.326 (утилита для переноса акка в китайском бс с appgallery на wechat/qq)

### ISSUE THREAD

**Issue by KitenokGene** [tailsjs/brawl-stars-assets#4]
https://mega.nz/file/HQ4D1b4Y#O4s5majII98fTpaOgeE969TvYIUBP5O3KN7djnLllLw
(я хз зачем они кладут ассеты если там только webview новостей, ну ладно)

**Comment by tailsjs** [comment]
Разве нечто подобное я не заливал уже? https://github.com/tailsjs/brawl-stars-assets/tree/master/CN-48.326

**Comment by KitenokGene** [comment]
хз, мб они отличаются чем-то, не чекал

**Comment by tailsjs** [comment]
Просто я сам попытался искать эту утилиту, по итогу я нашёл 48.326
