### ISSUE TITLE
Brawl Stars Chinese Version (v52.8.3)

### ISSUE THREAD

**Issue by oArthurEmilio** [tailsjs/brawl-stars-assets#5]
>

> `download:`
>
>_[https://www.mediafire.com/file/k4r615bpq9n2312/10040714_com.tencent.tmgp.supercell.brawlstars_a2887150_52.8.3_0dNt0S.apk/file](download-link)_

### _obs:_ have installed `QQ/WECHAT` to authorize (Login), and this is not optional, IS NEDEED.

**Comment by tailsjs** [comment]
Already have [52.8.3](https://github.com/tailsjs/brawl-stars-assets/tree/master/CN-52.8.3)
